/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package lemurproject.indri;

public class QueryAnnotation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QueryAnnotation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QueryAnnotation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        indriJNI.delete_QueryAnnotation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  
/**
@return QueryAnnotationNodes for the query tree.
@throws Exception if a lemur::api::Exception was thrown by the JNI library.
*/
public QueryAnnotationNode getQueryTree() throws java.lang.Exception {
  return indriJNI.QueryAnnotation_getQueryTree(swigCPtr, this);
}

  
/**
@return Annotations for the query tree.
@throws Exception if a lemur::api::Exception was thrown by the JNI library.
*/
public java.util.Map getAnnotations() throws java.lang.Exception {
  return indriJNI.QueryAnnotation_getAnnotations(swigCPtr, this);
}

  
/**
@return ScoredExtentResults for the query tree.
@throws Exception if a lemur::api::Exception was thrown by the JNI library.
*/
public ScoredExtentResult[] getResults() throws java.lang.Exception {
  return indriJNI.QueryAnnotation_getResults(swigCPtr, this);
}

  
/**
@return ScoredExtentResults for the query tree.
@throws Exception if a lemur::api::Exception was thrown by the JNI library.
*/
public QueryAnnotation() {
    this(indriJNI.new_QueryAnnotation(), true);
  }

}
