/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: interface/indri.i

package indri_go

// #cgo CXXFLAGS: -DPACKAGE_NAME="Indri" -DPACKAGE_TARNAME="indri" -DPACKAGE_VERSION="5.13" -DPACKAGE_STRING="Indri 5.13" -DPACKAGE_BUGREPORT="project@lemurproject.org" -DPACKAGE_URL="" -DINDRI_STANDALONE=1 -DHAVE_LIBM=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBZ=1 -DHAVE_NAMESPACES=1 -DISNAN_IN_NAMESPACE_STD=1 -DISNAN_IN_NAMESPACE_GNU_CXX=0 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_FSEEKO=1 -DHAVE_EXT_ATOMICITY_H=1 -DP_NEEDS_GNU_CXX_NAMESPACE=1 -DHAVE_MKSTEMP=1 -DHAVE_MKSTEMPS=1  -g -O3 -I/home/tavit/usr/include -fPIC
// #cgo LDFLAGS: -g -O3 -L/home/tavit/usr/lib -lindri -lz -lpthread -lm  -shared -fPIC
import "C"

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef long long swig_type_16;
typedef _gostring_ swig_type_17;
typedef long long swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef long long swig_type_28;
typedef _gostring_ swig_type_29;
typedef long long swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef _gostring_ swig_type_36;
typedef _gostring_ swig_type_37;
typedef long long swig_type_38;
typedef _gostring_ swig_type_39;
typedef _gostring_ swig_type_40;
typedef _gostring_ swig_type_41;
typedef _gostring_ swig_type_42;
typedef _gostring_ swig_type_43;
typedef _gostring_ swig_type_44;
typedef _gostring_ swig_type_45;
typedef _gostring_ swig_type_46;
typedef long long swig_type_47;
typedef long long swig_type_48;
typedef _gostring_ swig_type_49;
typedef long long swig_type_50;
typedef _gostring_ swig_type_51;
typedef _gostring_ swig_type_52;
typedef long long swig_type_53;
typedef long long swig_type_54;
typedef _gostring_ swig_type_55;
typedef _gostring_ swig_type_56;
typedef _gostring_ swig_type_57;
typedef _gostring_ swig_type_58;
typedef _gostring_ swig_type_59;
typedef _gostring_ swig_type_60;
typedef _gostring_ swig_type_61;
typedef _gostring_ swig_type_62;
typedef _gostring_ swig_type_63;
typedef _gostring_ swig_type_64;
typedef _gostring_ swig_type_65;
typedef _gostring_ swig_type_66;
typedef _gostring_ swig_type_67;
typedef _gostring_ swig_type_68;
typedef long long swig_type_69;
typedef long long swig_type_70;
typedef _gostring_ swig_type_71;
typedef long long swig_type_72;
typedef _gostring_ swig_type_73;
typedef _gostring_ swig_type_74;
typedef long long swig_type_75;
typedef _gostring_ swig_type_76;
typedef _gostring_ swig_type_77;
typedef _gostring_ swig_type_78;
typedef _gostring_ swig_type_79;
typedef _gostring_ swig_type_80;
typedef _gostring_ swig_type_81;
typedef _gostring_ swig_type_82;
typedef _gostring_ swig_type_83;
typedef _gostring_ swig_type_84;
typedef _gostring_ swig_type_85;
typedef _gostring_ swig_type_86;
typedef _gostring_ swig_type_87;
typedef _gostring_ swig_type_88;
typedef _gostring_ swig_type_89;
typedef _gostring_ swig_type_90;
typedef _gostring_ swig_type_91;
typedef _gostring_ swig_type_92;
typedef _gostring_ swig_type_93;
typedef _gostring_ swig_type_94;
typedef _gostring_ swig_type_95;
typedef _gostring_ swig_type_96;
typedef _gostring_ swig_type_97;
typedef _gostring_ swig_type_98;
typedef _gostring_ swig_type_99;
typedef _gostring_ swig_type_100;
typedef _gostring_ swig_type_101;
typedef _gostring_ swig_type_102;
typedef _gostring_ swig_type_103;
typedef _gostring_ swig_type_104;
typedef _gostring_ swig_type_105;
typedef _gostring_ swig_type_106;
typedef long long swig_type_107;
typedef _gostring_ swig_type_108;
typedef _gostring_ swig_type_109;
typedef _gostring_ swig_type_110;
typedef _gostring_ swig_type_111;
typedef _gostring_ swig_type_112;
typedef _gostring_ swig_type_113;
typedef _gostring_ swig_type_114;
typedef _gostring_ swig_type_115;
typedef _gostring_ swig_type_116;
extern void _wrap_Swig_free_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_indri_go_8c4c74c3cec9541e(swig_intgo arg1);
extern uintptr_t _wrap_new_IntVector__SWIG_0_indri_go_8c4c74c3cec9541e(void);
extern uintptr_t _wrap_new_IntVector__SWIG_1_indri_go_8c4c74c3cec9541e(swig_type_1 arg1);
extern swig_type_2 _wrap_IntVector_size_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_type_3 _wrap_IntVector_capacity_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_IntVector_reserve_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_4 arg2);
extern _Bool _wrap_IntVector_isEmpty_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_IntVector_clear_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_IntVector_add_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_IntVector_get_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_IntVector_set_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_delete_IntVector_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_new_StringVector__SWIG_0_indri_go_8c4c74c3cec9541e(void);
extern uintptr_t _wrap_new_StringVector__SWIG_1_indri_go_8c4c74c3cec9541e(swig_type_5 arg1);
extern swig_type_6 _wrap_StringVector_size_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_type_7 _wrap_StringVector_capacity_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_StringVector_reserve_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_8 arg2);
extern _Bool _wrap_StringVector_isEmpty_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_StringVector_clear_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_StringVector_add_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_9 arg2);
extern swig_type_10 _wrap_StringVector_get_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_StringVector_set_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2, swig_type_11 arg3);
extern void _wrap_delete_StringVector_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_new_Parameters_indri_go_8c4c74c3cec9541e(void);
extern void _wrap_delete_Parameters_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_Parameters_set_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_12 arg2);
extern _Bool _wrap_Parameters_get_bool_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_13 arg2, _Bool arg3);
extern swig_intgo _wrap_Parameters_get_int_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_14 arg2, swig_intgo arg3);
extern double _wrap_Parameters_get_double_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_15 arg2, double arg3);
extern swig_type_16 _wrap_Parameters_get_INT64_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_17 arg2, swig_type_18 arg3);
extern swig_type_19 _wrap_Parameters_get_string_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_20 arg2, swig_type_21 arg3);
extern void _wrap_Parameters_remove_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_22 arg2);
extern void _wrap_Parameters_set_bool_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_23 arg2, _Bool arg3);
extern void _wrap_Parameters_set_string_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_24 arg2, swig_type_25 arg3);
extern void _wrap_Parameters_set_int_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_26 arg2, swig_intgo arg3);
extern void _wrap_Parameters_set_UINT64_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_27 arg2, swig_type_28 arg3);
extern void _wrap_Parameters_set_double_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_29 arg2, double arg3);
extern void _wrap_Parameters_clear_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_type_30 _wrap_Parameters_size_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern _Bool _wrap_Parameters_exists_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_31 arg2);
extern void _wrap_Parameters_load_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_32 arg2);
extern void _wrap_TermExtent_begin_set_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_TermExtent_begin_get_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_TermExtent_end_set_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_TermExtent_end_get_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_delete_TermExtent_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_new_TermExtent_indri_go_8c4c74c3cec9541e(void);
extern void _wrap_delete_ScoredExtentResult_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_new_ScoredExtentResult_indri_go_8c4c74c3cec9541e(void);
extern void _wrap_delete_ParsedDocument_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_type_33 _wrap_ParsedDocument_getContent_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_new_ParsedDocument_indri_go_8c4c74c3cec9541e(void);
extern uintptr_t _wrap_new_QueryAnnotationNode_indri_go_8c4c74c3cec9541e(void);
extern void _wrap_delete_QueryAnnotationNode_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_QueryAnnotation_getQueryTree_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_QueryAnnotation_getAnnotations_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_QueryAnnotation_getResults_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_delete_QueryAnnotation_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_new_QueryEnvironment_indri_go_8c4c74c3cec9541e(void);
extern void _wrap_QueryEnvironment_addServer_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_34 arg2);
extern void _wrap_QueryEnvironment_addIndex_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_35 arg2);
extern void _wrap_QueryEnvironment_removeServer_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_36 arg2);
extern void _wrap_QueryEnvironment_removeIndex_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_37 arg2);
extern void _wrap_QueryEnvironment_close_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_QueryEnvironment_setMemory_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_38 arg2);
extern void _wrap_QueryEnvironment_setScoringRules_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_QueryEnvironment_setStopwords_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_QueryEnvironment_runQuery__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_39 arg2, swig_intgo arg3);
extern uintptr_t _wrap_QueryEnvironment_runQuery__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_40 arg2, uintptr_t arg3, swig_intgo arg4);
extern uintptr_t _wrap_QueryEnvironment_runAnnotatedQuery__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_41 arg2, swig_intgo arg3);
extern uintptr_t _wrap_QueryEnvironment_runAnnotatedQuery__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_42 arg2, uintptr_t arg3, swig_intgo arg4);
extern uintptr_t _wrap_QueryEnvironment_documents__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_QueryEnvironment_documents__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_QueryEnvironment_documentMetadata__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2, swig_type_43 arg3);
extern uintptr_t _wrap_QueryEnvironment_documentMetadata__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2, swig_type_44 arg3);
extern uintptr_t _wrap_QueryEnvironment_documentIDsFromMetadata_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_45 arg2, uintptr_t arg3);
extern uintptr_t _wrap_QueryEnvironment_documentsFromMetadata_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_46 arg2, uintptr_t arg3);
extern swig_type_47 _wrap_QueryEnvironment_termCount__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_type_48 _wrap_QueryEnvironment_termCount__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_49 arg2);
extern swig_type_50 _wrap_QueryEnvironment_termFieldCount_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_51 arg2, swig_type_52 arg3);
extern uintptr_t _wrap_QueryEnvironment_fieldList_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_type_53 _wrap_QueryEnvironment_documentCount__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_type_54 _wrap_QueryEnvironment_documentCount__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_55 arg2);
extern uintptr_t _wrap_QueryEnvironment_documentVectors_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern double _wrap_QueryEnvironment_expressionCount__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_56 arg2, swig_type_57 arg3);
extern double _wrap_QueryEnvironment_expressionCount__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_58 arg2);
extern double _wrap_QueryEnvironment_documentExpressionCount__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_59 arg2, swig_type_60 arg3);
extern double _wrap_QueryEnvironment_documentExpressionCount__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_61 arg2);
extern uintptr_t _wrap_QueryEnvironment_expressionList__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_62 arg2, swig_type_63 arg3);
extern uintptr_t _wrap_QueryEnvironment_expressionList__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_64 arg2);
extern swig_intgo _wrap_QueryEnvironment_documentLength_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_QueryEnvironment_setFormulationParameters_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern swig_type_65 _wrap_QueryEnvironment_reformulateQuery_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_66 arg2);
extern swig_type_67 _wrap_QueryEnvironment_stemTerm_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_68 arg2);
extern swig_type_69 _wrap_QueryEnvironment_termCountUnique_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_type_70 _wrap_QueryEnvironment_stemCount_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_71 arg2);
extern swig_type_72 _wrap_QueryEnvironment_stemFieldCount_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_73 arg2, swig_type_74 arg3);
extern swig_type_75 _wrap_QueryEnvironment_documentStemCount_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_76 arg2);
extern void _wrap_delete_QueryEnvironment_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_delete_QueryExpander_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_QueryExpander_runExpandedQuery__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_77 arg2, swig_intgo arg3, _Bool arg4);
extern uintptr_t _wrap_QueryExpander_runExpandedQuery__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_78 arg2, swig_intgo arg3);
extern swig_type_79 _wrap_QueryExpander_expand_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_80 arg2, uintptr_t arg3);
extern uintptr_t _wrap_new_RMExpander_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern swig_type_81 _wrap_RMExpander_expand_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_82 arg2, uintptr_t arg3);
extern void _wrap_delete_RMExpander_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_RMExpander_runExpandedQuery__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t _swig_base, swig_type_83 arg1, swig_intgo arg2, _Bool arg3);
extern uintptr_t _wrap_RMExpander_runExpandedQuery__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t _swig_base, swig_type_84 arg1, swig_intgo arg2);
extern uintptr_t _wrap_new_PonteExpander_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern swig_type_85 _wrap_PonteExpander_expand_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_86 arg2, uintptr_t arg3);
extern void _wrap_delete_PonteExpander_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern uintptr_t _wrap_PonteExpander_runExpandedQuery__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t _swig_base, swig_type_83 arg1, swig_intgo arg2, _Bool arg3);
extern uintptr_t _wrap_PonteExpander_runExpandedQuery__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t _swig_base, swig_type_84 arg1, swig_intgo arg2);
extern swig_intgo _wrap_FileOpen_IndexStatus_indri_go_8c4c74c3cec9541e(void);
extern swig_intgo _wrap_FileSkip_IndexStatus_indri_go_8c4c74c3cec9541e(void);
extern swig_intgo _wrap_FileError_IndexStatus_indri_go_8c4c74c3cec9541e(void);
extern swig_intgo _wrap_FileClose_IndexStatus_indri_go_8c4c74c3cec9541e(void);
extern swig_intgo _wrap_DocumentCount_IndexStatus_indri_go_8c4c74c3cec9541e(void);
extern void _wrap_delete_IndexStatus_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_IndexStatus_status_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2, swig_type_87 arg3, swig_type_88 arg4, swig_intgo arg5, swig_intgo arg6);
extern uintptr_t _wrap_new_IndexEnvironment_indri_go_8c4c74c3cec9541e(void);
extern void _wrap_delete_IndexEnvironment_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_IndexEnvironment_setDocumentRoot_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_89 arg2);
extern void _wrap_IndexEnvironment_setAnchorTextPath_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_90 arg2);
extern void _wrap_IndexEnvironment_setOffsetMetadataPath_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_91 arg2);
extern void _wrap_IndexEnvironment_setOffsetAnnotationsPath_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_92 arg2);
extern void _wrap_IndexEnvironment_addFileClass__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_93 arg2, swig_type_94 arg3, swig_type_95 arg4, swig_type_96 arg5, swig_type_97 arg6, swig_type_98 arg7, swig_type_99 arg8, uintptr_t arg9, uintptr_t arg10, uintptr_t arg11, uintptr_t arg12, uintptr_t arg13);
extern uintptr_t _wrap_IndexEnvironment_getFileClassSpec_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_100 arg2);
extern void _wrap_IndexEnvironment_addFileClass__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IndexEnvironment_deleteDocument_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_IndexEnvironment_setIndexedFields_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IndexEnvironment_setNumericField__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_101 arg2, _Bool arg3, swig_type_102 arg4);
extern void _wrap_IndexEnvironment_setNumericField__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_103 arg2, _Bool arg3);
extern void _wrap_IndexEnvironment_setOrdinalField_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_104 arg2, _Bool arg3);
extern void _wrap_IndexEnvironment_setParentalField_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_105 arg2, _Bool arg3);
extern void _wrap_IndexEnvironment_setMetadataIndexedFields_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_IndexEnvironment_setStopwords_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IndexEnvironment_setStemmer_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_106 arg2);
extern void _wrap_IndexEnvironment_setMemory_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_107 arg2);
extern void _wrap_IndexEnvironment_setNormalization_indri_go_8c4c74c3cec9541e(uintptr_t arg1, _Bool arg2);
extern void _wrap_IndexEnvironment_setStoreDocs_indri_go_8c4c74c3cec9541e(uintptr_t arg1, _Bool arg2);
extern void _wrap_IndexEnvironment_create__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_108 arg2, uintptr_t arg3);
extern void _wrap_IndexEnvironment_create__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_109 arg2);
extern void _wrap_IndexEnvironment_open__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_110 arg2, uintptr_t arg3);
extern void _wrap_IndexEnvironment_open__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_111 arg2);
extern void _wrap_IndexEnvironment_close_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern void _wrap_IndexEnvironment_addFile__SWIG_0_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_112 arg2);
extern void _wrap_IndexEnvironment_addFile__SWIG_1_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_113 arg2, swig_type_114 arg3);
extern swig_intgo _wrap_IndexEnvironment_addString_indri_go_8c4c74c3cec9541e(uintptr_t arg1, swig_type_115 arg2, swig_type_116 arg3, uintptr_t arg4);
extern swig_intgo _wrap_IndexEnvironment_addParsedDocument_indri_go_8c4c74c3cec9541e(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_IndexEnvironment_documentsIndexed_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
extern swig_intgo _wrap_IndexEnvironment_documentsSeen_indri_go_8c4c74c3cec9541e(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_indri_go_8c4c74c3cec9541e(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrIntVector uintptr

func (p SwigcptrIntVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIntVector) SwigIsIntVector() {
}

func NewIntVector__SWIG_0() (_swig_ret IntVector) {
	var swig_r IntVector
	swig_r = (IntVector)(SwigcptrIntVector(C._wrap_new_IntVector__SWIG_0_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

func NewIntVector__SWIG_1(arg1 int64) (_swig_ret IntVector) {
	var swig_r IntVector
	_swig_i_0 := arg1
	swig_r = (IntVector)(SwigcptrIntVector(C._wrap_new_IntVector__SWIG_1_indri_go_8c4c74c3cec9541e(C.swig_type_1(_swig_i_0))))
	return swig_r
}

func NewIntVector(a ...interface{}) IntVector {
	argc := len(a)
	if argc == 0 {
		return NewIntVector__SWIG_0()
	}
	if argc == 1 {
		return NewIntVector__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIntVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_IntVector_size_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIntVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_IntVector_capacity_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIntVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IntVector_reserve_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrIntVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_IntVector_isEmpty_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIntVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_IntVector_clear_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrIntVector) Add(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IntVector_add_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrIntVector) Get(arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_IntVector_get_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrIntVector) Set(arg2 int, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_IntVector_set_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func DeleteIntVector(arg1 IntVector) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IntVector_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

type IntVector interface {
	Swigcptr() uintptr
	SwigIsIntVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 int)
	Get(arg2 int) (_swig_ret int)
	Set(arg2 int, arg3 int)
}

type SwigcptrStringVector uintptr

func (p SwigcptrStringVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStringVector) SwigIsStringVector() {
}

func NewStringVector__SWIG_0() (_swig_ret StringVector) {
	var swig_r StringVector
	swig_r = (StringVector)(SwigcptrStringVector(C._wrap_new_StringVector__SWIG_0_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

func NewStringVector__SWIG_1(arg1 int64) (_swig_ret StringVector) {
	var swig_r StringVector
	_swig_i_0 := arg1
	swig_r = (StringVector)(SwigcptrStringVector(C._wrap_new_StringVector__SWIG_1_indri_go_8c4c74c3cec9541e(C.swig_type_5(_swig_i_0))))
	return swig_r
}

func NewStringVector(a ...interface{}) StringVector {
	argc := len(a)
	if argc == 0 {
		return NewStringVector__SWIG_0()
	}
	if argc == 1 {
		return NewStringVector__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrStringVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_StringVector_size_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_StringVector_capacity_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_StringVector_reserve_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1))
}

func (arg1 SwigcptrStringVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_StringVector_isEmpty_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_StringVector_clear_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrStringVector) Add(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_StringVector_add_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrStringVector) Get(arg2 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_StringVector_get_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrStringVector) Set(arg2 int, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_StringVector_set_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func DeleteStringVector(arg1 StringVector) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_StringVector_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

type StringVector interface {
	Swigcptr() uintptr
	SwigIsStringVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 string)
	Get(arg2 int) (_swig_ret string)
	Set(arg2 int, arg3 string)
}

type SwigcptrParameters uintptr

func (p SwigcptrParameters) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrParameters) SwigIsParameters() {
}

func NewParameters() (_swig_ret Parameters) {
	var swig_r Parameters
	swig_r = (Parameters)(SwigcptrParameters(C._wrap_new_Parameters_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

func DeleteParameters(arg1 Parameters) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Parameters_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrParameters) Set(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Parameters_set_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrParameters) Get_bool(arg2 string, arg3 bool) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (bool)(C._wrap_Parameters_get_bool_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_1)), C._Bool(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrParameters) Get_int(arg2 string, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_Parameters_get_int_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrParameters) Get_double(arg2 string, arg3 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_Parameters_get_double_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_15)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrParameters) Get_INT64(arg2 string, arg3 int64) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int64)(C._wrap_Parameters_get_INT64_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_1)), C.swig_type_18(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrParameters) Get_string(arg2 string, arg3 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Parameters_get_string_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_20)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_21)(unsafe.Pointer(&_swig_i_2)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrParameters) Remove(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Parameters_remove_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrParameters) Set_bool(arg2 string, arg3 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Parameters_set_bool_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_23)(unsafe.Pointer(&_swig_i_1)), C._Bool(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrParameters) Set_string(arg2 string, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Parameters_set_string_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_24)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_25)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func (arg1 SwigcptrParameters) Set_int(arg2 string, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Parameters_set_int_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_26)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrParameters) Set_UINT64(arg2 string, arg3 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Parameters_set_UINT64_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_27)(unsafe.Pointer(&_swig_i_1)), C.swig_type_28(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrParameters) Set_double(arg2 string, arg3 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Parameters_set_double_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_29)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrParameters) Clear() {
	_swig_i_0 := arg1
	C._wrap_Parameters_clear_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrParameters) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Parameters_size_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrParameters) Exists(arg2 string) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_Parameters_exists_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_31)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrParameters) Load(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Parameters_load_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_32)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

type Parameters interface {
	Swigcptr() uintptr
	SwigIsParameters()
	Set(arg2 string)
	Get_bool(arg2 string, arg3 bool) (_swig_ret bool)
	Get_int(arg2 string, arg3 int) (_swig_ret int)
	Get_double(arg2 string, arg3 float64) (_swig_ret float64)
	Get_INT64(arg2 string, arg3 int64) (_swig_ret int64)
	Get_string(arg2 string, arg3 string) (_swig_ret string)
	Remove(arg2 string)
	Set_bool(arg2 string, arg3 bool)
	Set_string(arg2 string, arg3 string)
	Set_int(arg2 string, arg3 int)
	Set_UINT64(arg2 string, arg3 int64)
	Set_double(arg2 string, arg3 float64)
	Clear()
	Size() (_swig_ret int64)
	Exists(arg2 string) (_swig_ret bool)
	Load(arg2 string)
}

type SwigcptrTermExtent uintptr

func (p SwigcptrTermExtent) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTermExtent) SwigIsTermExtent() {
}

func (arg1 SwigcptrTermExtent) SetBegin(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TermExtent_begin_set_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTermExtent) GetBegin() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_TermExtent_begin_get_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTermExtent) SetEnd(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TermExtent_end_set_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTermExtent) GetEnd() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_TermExtent_end_get_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteTermExtent(arg1 TermExtent) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_TermExtent_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func NewTermExtent() (_swig_ret TermExtent) {
	var swig_r TermExtent
	swig_r = (TermExtent)(SwigcptrTermExtent(C._wrap_new_TermExtent_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

type TermExtent interface {
	Swigcptr() uintptr
	SwigIsTermExtent()
	SetBegin(arg2 int)
	GetBegin() (_swig_ret int)
	SetEnd(arg2 int)
	GetEnd() (_swig_ret int)
}

type SwigcptrScoredExtentResult uintptr

func (p SwigcptrScoredExtentResult) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrScoredExtentResult) SwigIsScoredExtentResult() {
}

func DeleteScoredExtentResult(arg1 ScoredExtentResult) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ScoredExtentResult_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func NewScoredExtentResult() (_swig_ret ScoredExtentResult) {
	var swig_r ScoredExtentResult
	swig_r = (ScoredExtentResult)(SwigcptrScoredExtentResult(C._wrap_new_ScoredExtentResult_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

type ScoredExtentResult interface {
	Swigcptr() uintptr
	SwigIsScoredExtentResult()
}

type SwigcptrParsedDocument uintptr

func (p SwigcptrParsedDocument) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrParsedDocument) SwigIsParsedDocument() {
}

func DeleteParsedDocument(arg1 ParsedDocument) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ParsedDocument_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrParsedDocument) GetContent() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ParsedDocument_getContent_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewParsedDocument() (_swig_ret ParsedDocument) {
	var swig_r ParsedDocument
	swig_r = (ParsedDocument)(SwigcptrParsedDocument(C._wrap_new_ParsedDocument_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

type ParsedDocument interface {
	Swigcptr() uintptr
	SwigIsParsedDocument()
	GetContent() (_swig_ret string)
}

type SwigcptrQueryAnnotationNode uintptr

func (p SwigcptrQueryAnnotationNode) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrQueryAnnotationNode) SwigIsQueryAnnotationNode() {
}

func NewQueryAnnotationNode() (_swig_ret QueryAnnotationNode) {
	var swig_r QueryAnnotationNode
	swig_r = (QueryAnnotationNode)(SwigcptrQueryAnnotationNode(C._wrap_new_QueryAnnotationNode_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

func DeleteQueryAnnotationNode(arg1 QueryAnnotationNode) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_QueryAnnotationNode_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

type QueryAnnotationNode interface {
	Swigcptr() uintptr
	SwigIsQueryAnnotationNode()
}

type SwigcptrQueryAnnotation uintptr

func (p SwigcptrQueryAnnotation) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrQueryAnnotation) SwigIsQueryAnnotation() {
}

func (arg1 SwigcptrQueryAnnotation) GetQueryTree() (_swig_ret QueryAnnotationNode) {
	var swig_r QueryAnnotationNode
	_swig_i_0 := arg1
	swig_r = (QueryAnnotationNode)(SwigcptrQueryAnnotationNode(C._wrap_QueryAnnotation_getQueryTree_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrQueryAnnotation) GetAnnotations() (_swig_ret Indri_infnet_EvaluatorNode_MResults) {
	var swig_r Indri_infnet_EvaluatorNode_MResults
	_swig_i_0 := arg1
	swig_r = (Indri_infnet_EvaluatorNode_MResults)(SwigcptrIndri_infnet_EvaluatorNode_MResults(C._wrap_QueryAnnotation_getAnnotations_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrQueryAnnotation) GetResults() (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_QueryAnnotation_getResults_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteQueryAnnotation(arg1 QueryAnnotation) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_QueryAnnotation_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

type QueryAnnotation interface {
	Swigcptr() uintptr
	SwigIsQueryAnnotation()
	GetQueryTree() (_swig_ret QueryAnnotationNode)
	GetAnnotations() (_swig_ret Indri_infnet_EvaluatorNode_MResults)
	GetResults() (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)
}

type SwigcptrQueryEnvironment uintptr

func (p SwigcptrQueryEnvironment) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrQueryEnvironment) SwigIsQueryEnvironment() {
}

func NewQueryEnvironment() (_swig_ret QueryEnvironment) {
	var swig_r QueryEnvironment
	swig_r = (QueryEnvironment)(SwigcptrQueryEnvironment(C._wrap_new_QueryEnvironment_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) AddServer(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_QueryEnvironment_addServer_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_34)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrQueryEnvironment) AddIndex(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_QueryEnvironment_addIndex_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_35)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrQueryEnvironment) RemoveServer(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_QueryEnvironment_removeServer_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_36)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrQueryEnvironment) RemoveIndex(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_QueryEnvironment_removeIndex_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_37)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrQueryEnvironment) Close() {
	_swig_i_0 := arg1
	C._wrap_QueryEnvironment_close_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrQueryEnvironment) SetMemory(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_QueryEnvironment_setMemory_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_type_38(_swig_i_1))
}

func (arg1 SwigcptrQueryEnvironment) SetScoringRules(arg2 StringVector) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_QueryEnvironment_setScoringRules_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrQueryEnvironment) SetStopwords(arg2 StringVector) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_QueryEnvironment_setStopwords_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrQueryEnvironment) RunQuery__SWIG_0(arg2 string, arg3 int) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_QueryEnvironment_runQuery__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_39)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) RunQuery__SWIG_1(arg2 string, arg3 IntVector, arg4 int) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_QueryEnvironment_runQuery__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_40)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2), C.swig_intgo(_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (p SwigcptrQueryEnvironment) RunQuery(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_ {
	argc := len(a)
	if argc == 2 {
		return p.RunQuery__SWIG_0(a[0].(string), a[1].(int))
	}
	if argc == 3 {
		return p.RunQuery__SWIG_1(a[0].(string), a[1].(IntVector), a[2].(int))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) RunAnnotatedQuery__SWIG_0(arg2 string, arg3 int) (_swig_ret QueryAnnotation) {
	var swig_r QueryAnnotation
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (QueryAnnotation)(SwigcptrQueryAnnotation(C._wrap_QueryEnvironment_runAnnotatedQuery__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_41)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) RunAnnotatedQuery__SWIG_1(arg2 string, arg3 IntVector, arg4 int) (_swig_ret QueryAnnotation) {
	var swig_r QueryAnnotation
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (QueryAnnotation)(SwigcptrQueryAnnotation(C._wrap_QueryEnvironment_runAnnotatedQuery__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_42)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2), C.swig_intgo(_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (p SwigcptrQueryEnvironment) RunAnnotatedQuery(a ...interface{}) QueryAnnotation {
	argc := len(a)
	if argc == 2 {
		return p.RunAnnotatedQuery__SWIG_0(a[0].(string), a[1].(int))
	}
	if argc == 3 {
		return p.RunAnnotatedQuery__SWIG_1(a[0].(string), a[1].(IntVector), a[2].(int))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) Documents__SWIG_0(arg2 IntVector) (_swig_ret Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_) {
	var swig_r Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_)(SwigcptrStd_vector_Sl_indri_api_ParsedDocument_Sm__Sg_(C._wrap_QueryEnvironment_documents__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) Documents__SWIG_1(arg2 Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) (_swig_ret Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_) {
	var swig_r Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_)(SwigcptrStd_vector_Sl_indri_api_ParsedDocument_Sm__Sg_(C._wrap_QueryEnvironment_documents__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (p SwigcptrQueryEnvironment) Documents(a ...interface{}) Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_ {
	argc := len(a)
	if argc == 1 {
		if _, ok := a[0].(SwigcptrIntVector); !ok {
			goto check_1
		}
		return p.Documents__SWIG_0(a[0].(IntVector))
	}
check_1:
	if argc == 1 {
		return p.Documents__SWIG_1(a[0].(Std_vector_Sl_indri_api_ScoredExtentResult_Sg_))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) DocumentMetadata__SWIG_0(arg2 IntVector, arg3 string) (_swig_ret StringVector) {
	var swig_r StringVector
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (StringVector)(SwigcptrStringVector(C._wrap_QueryEnvironment_documentMetadata__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), *(*C.swig_type_43)(unsafe.Pointer(&_swig_i_2)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) DocumentMetadata__SWIG_1(arg2 Std_vector_Sl_indri_api_ScoredExtentResult_Sg_, arg3 string) (_swig_ret StringVector) {
	var swig_r StringVector
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (StringVector)(SwigcptrStringVector(C._wrap_QueryEnvironment_documentMetadata__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), *(*C.swig_type_44)(unsafe.Pointer(&_swig_i_2)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (p SwigcptrQueryEnvironment) DocumentMetadata(a ...interface{}) StringVector {
	argc := len(a)
	if argc == 2 {
		if _, ok := a[0].(SwigcptrIntVector); !ok {
			goto check_1
		}
		return p.DocumentMetadata__SWIG_0(a[0].(IntVector), a[1].(string))
	}
check_1:
	if argc == 2 {
		return p.DocumentMetadata__SWIG_1(a[0].(Std_vector_Sl_indri_api_ScoredExtentResult_Sg_), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) DocumentIDsFromMetadata(arg2 string, arg3 StringVector) (_swig_ret IntVector) {
	var swig_r IntVector
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (IntVector)(SwigcptrIntVector(C._wrap_QueryEnvironment_documentIDsFromMetadata_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_45)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) DocumentsFromMetadata(arg2 string, arg3 StringVector) (_swig_ret Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_) {
	var swig_r Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_)(SwigcptrStd_vector_Sl_indri_api_ParsedDocument_Sm__Sg_(C._wrap_QueryEnvironment_documentsFromMetadata_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_46)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) TermCount__SWIG_0() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_QueryEnvironment_termCount__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) TermCount__SWIG_1(arg2 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_QueryEnvironment_termCount__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_49)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (p SwigcptrQueryEnvironment) TermCount(a ...interface{}) int64 {
	argc := len(a)
	if argc == 0 {
		return p.TermCount__SWIG_0()
	}
	if argc == 1 {
		return p.TermCount__SWIG_1(a[0].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) TermFieldCount(arg2 string, arg3 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int64)(C._wrap_QueryEnvironment_termFieldCount_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_51)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_52)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) FieldList() (_swig_ret StringVector) {
	var swig_r StringVector
	_swig_i_0 := arg1
	swig_r = (StringVector)(SwigcptrStringVector(C._wrap_QueryEnvironment_fieldList_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) DocumentCount__SWIG_0() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_QueryEnvironment_documentCount__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) DocumentCount__SWIG_1(arg2 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_QueryEnvironment_documentCount__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_55)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (p SwigcptrQueryEnvironment) DocumentCount(a ...interface{}) int64 {
	argc := len(a)
	if argc == 0 {
		return p.DocumentCount__SWIG_0()
	}
	if argc == 1 {
		return p.DocumentCount__SWIG_1(a[0].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) DocumentVectors(arg2 IntVector) (_swig_ret Std_vector_Sl_indri_api_DocumentVector_Sm__Sg_) {
	var swig_r Std_vector_Sl_indri_api_DocumentVector_Sm__Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Std_vector_Sl_indri_api_DocumentVector_Sm__Sg_)(SwigcptrStd_vector_Sl_indri_api_DocumentVector_Sm__Sg_(C._wrap_QueryEnvironment_documentVectors_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) ExpressionCount__SWIG_0(arg2 string, arg3 string) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_QueryEnvironment_expressionCount__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_56)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_57)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) ExpressionCount__SWIG_1(arg2 string) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_QueryEnvironment_expressionCount__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_58)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (p SwigcptrQueryEnvironment) ExpressionCount(a ...interface{}) float64 {
	argc := len(a)
	if argc == 1 {
		return p.ExpressionCount__SWIG_1(a[0].(string))
	}
	if argc == 2 {
		return p.ExpressionCount__SWIG_0(a[0].(string), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) DocumentExpressionCount__SWIG_0(arg2 string, arg3 string) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_QueryEnvironment_documentExpressionCount__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_59)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_60)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) DocumentExpressionCount__SWIG_1(arg2 string) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_QueryEnvironment_documentExpressionCount__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_61)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (p SwigcptrQueryEnvironment) DocumentExpressionCount(a ...interface{}) float64 {
	argc := len(a)
	if argc == 1 {
		return p.DocumentExpressionCount__SWIG_1(a[0].(string))
	}
	if argc == 2 {
		return p.DocumentExpressionCount__SWIG_0(a[0].(string), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) ExpressionList__SWIG_0(arg2 string, arg3 string) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_QueryEnvironment_expressionList__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_62)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_63)(unsafe.Pointer(&_swig_i_2)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) ExpressionList__SWIG_1(arg2 string) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_QueryEnvironment_expressionList__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_64)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (p SwigcptrQueryEnvironment) ExpressionList(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_ {
	argc := len(a)
	if argc == 1 {
		return p.ExpressionList__SWIG_1(a[0].(string))
	}
	if argc == 2 {
		return p.ExpressionList__SWIG_0(a[0].(string), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryEnvironment) DocumentLength(arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_QueryEnvironment_documentLength_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) SetFormulationParameters(arg2 Parameters) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_QueryEnvironment_setFormulationParameters_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrQueryEnvironment) ReformulateQuery(arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_QueryEnvironment_reformulateQuery_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_66)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrQueryEnvironment) StemTerm(arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_QueryEnvironment_stemTerm_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_68)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrQueryEnvironment) TermCountUnique() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_QueryEnvironment_termCountUnique_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) StemCount(arg2 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_QueryEnvironment_stemCount_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_71)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) StemFieldCount(arg2 string, arg3 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int64)(C._wrap_QueryEnvironment_stemFieldCount_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_73)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_74)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrQueryEnvironment) DocumentStemCount(arg2 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_QueryEnvironment_documentStemCount_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_76)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func DeleteQueryEnvironment(arg1 QueryEnvironment) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_QueryEnvironment_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

type QueryEnvironment interface {
	Swigcptr() uintptr
	SwigIsQueryEnvironment()
	AddServer(arg2 string)
	AddIndex(arg2 string)
	RemoveServer(arg2 string)
	RemoveIndex(arg2 string)
	Close()
	SetMemory(arg2 int64)
	SetScoringRules(arg2 StringVector)
	SetStopwords(arg2 StringVector)
	RunQuery(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	RunAnnotatedQuery(a ...interface{}) QueryAnnotation
	Documents(a ...interface{}) Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_
	DocumentMetadata(a ...interface{}) StringVector
	DocumentIDsFromMetadata(arg2 string, arg3 StringVector) (_swig_ret IntVector)
	DocumentsFromMetadata(arg2 string, arg3 StringVector) (_swig_ret Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_)
	TermCount(a ...interface{}) int64
	TermFieldCount(arg2 string, arg3 string) (_swig_ret int64)
	FieldList() (_swig_ret StringVector)
	DocumentCount(a ...interface{}) int64
	DocumentVectors(arg2 IntVector) (_swig_ret Std_vector_Sl_indri_api_DocumentVector_Sm__Sg_)
	ExpressionCount(a ...interface{}) float64
	DocumentExpressionCount(a ...interface{}) float64
	ExpressionList(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	DocumentLength(arg2 int) (_swig_ret int)
	SetFormulationParameters(arg2 Parameters)
	ReformulateQuery(arg2 string) (_swig_ret string)
	StemTerm(arg2 string) (_swig_ret string)
	TermCountUnique() (_swig_ret int64)
	StemCount(arg2 string) (_swig_ret int64)
	StemFieldCount(arg2 string, arg3 string) (_swig_ret int64)
	DocumentStemCount(arg2 string) (_swig_ret int64)
}

type SwigcptrQueryExpander uintptr

func (p SwigcptrQueryExpander) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrQueryExpander) SwigIsQueryExpander() {
}

func DeleteQueryExpander(arg1 QueryExpander) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_QueryExpander_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrQueryExpander) RunExpandedQuery__SWIG_0(arg2 string, arg3 int, arg4 bool) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_QueryExpander_runExpandedQuery__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_77)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), C._Bool(_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrQueryExpander) RunExpandedQuery__SWIG_1(arg2 string, arg3 int) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_QueryExpander_runExpandedQuery__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_78)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (p SwigcptrQueryExpander) RunExpandedQuery(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_ {
	argc := len(a)
	if argc == 2 {
		return p.RunExpandedQuery__SWIG_1(a[0].(string), a[1].(int))
	}
	if argc == 3 {
		return p.RunExpandedQuery__SWIG_0(a[0].(string), a[1].(int), a[2].(bool))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrQueryExpander) Expand(arg2 string, arg3 Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_QueryExpander_expand_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_80)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

type QueryExpander interface {
	Swigcptr() uintptr
	SwigIsQueryExpander()
	RunExpandedQuery(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	Expand(arg2 string, arg3 Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) (_swig_ret string)
}

type SwigcptrRMExpander uintptr

func (p SwigcptrRMExpander) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrRMExpander) SwigIsRMExpander() {
}

func NewRMExpander(arg1 QueryEnvironment, arg2 Parameters) (_swig_ret RMExpander) {
	var swig_r RMExpander
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (RMExpander)(SwigcptrRMExpander(C._wrap_new_RMExpander_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrRMExpander) Expand(arg2 string, arg3 Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_RMExpander_expand_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_82)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeleteRMExpander(arg1 RMExpander) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_RMExpander_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrRMExpander) RunExpandedQuery__SWIG_0(arg1 string, arg2 int, arg3 bool) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_RMExpander_runExpandedQuery__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_base), *(*C.swig_type_83)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1), C._Bool(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (_swig_base SwigcptrRMExpander) RunExpandedQuery__SWIG_1(arg1 string, arg2 int) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_RMExpander_runExpandedQuery__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_base), *(*C.swig_type_84)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (p SwigcptrRMExpander) RunExpandedQuery(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_ {
	argc := len(a)
	if argc == 2 {
		return p.RunExpandedQuery__SWIG_1(a[0].(string), a[1].(int))
	}
	if argc == 3 {
		return p.RunExpandedQuery__SWIG_0(a[0].(string), a[1].(int), a[2].(bool))
	}
	panic("No match for overloaded function call")
}

func (p SwigcptrRMExpander) SwigIsQueryExpander() {
}

func (p SwigcptrRMExpander) SwigGetQueryExpander() QueryExpander {
	return SwigcptrQueryExpander(p.Swigcptr())
}

type RMExpander interface {
	Swigcptr() uintptr
	SwigIsRMExpander()
	Expand(arg2 string, arg3 Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) (_swig_ret string)
	RunExpandedQuery(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	SwigIsQueryExpander()
	SwigGetQueryExpander() QueryExpander
}

type SwigcptrPonteExpander uintptr

func (p SwigcptrPonteExpander) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPonteExpander) SwigIsPonteExpander() {
}

func NewPonteExpander(arg1 QueryEnvironment, arg2 Parameters) (_swig_ret PonteExpander) {
	var swig_r PonteExpander
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (PonteExpander)(SwigcptrPonteExpander(C._wrap_new_PonteExpander_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrPonteExpander) Expand(arg2 string, arg3 Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PonteExpander_expand_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_86)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeletePonteExpander(arg1 PonteExpander) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_PonteExpander_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrPonteExpander) RunExpandedQuery__SWIG_0(arg1 string, arg2 int, arg3 bool) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_PonteExpander_runExpandedQuery__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_base), *(*C.swig_type_83)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1), C._Bool(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (_swig_base SwigcptrPonteExpander) RunExpandedQuery__SWIG_1(arg1 string, arg2 int) (_swig_ret Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) {
	var swig_r Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Std_vector_Sl_indri_api_ScoredExtentResult_Sg_)(SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_(C._wrap_PonteExpander_runExpandedQuery__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_base), *(*C.swig_type_84)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (p SwigcptrPonteExpander) RunExpandedQuery(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_ {
	argc := len(a)
	if argc == 2 {
		return p.RunExpandedQuery__SWIG_1(a[0].(string), a[1].(int))
	}
	if argc == 3 {
		return p.RunExpandedQuery__SWIG_0(a[0].(string), a[1].(int), a[2].(bool))
	}
	panic("No match for overloaded function call")
}

func (p SwigcptrPonteExpander) SwigIsQueryExpander() {
}

func (p SwigcptrPonteExpander) SwigGetQueryExpander() QueryExpander {
	return SwigcptrQueryExpander(p.Swigcptr())
}

type PonteExpander interface {
	Swigcptr() uintptr
	SwigIsPonteExpander()
	Expand(arg2 string, arg3 Std_vector_Sl_indri_api_ScoredExtentResult_Sg_) (_swig_ret string)
	RunExpandedQuery(a ...interface{}) Std_vector_Sl_indri_api_ScoredExtentResult_Sg_
	SwigIsQueryExpander()
	SwigGetQueryExpander() QueryExpander
}

type SwigcptrIndexStatus uintptr

func (p SwigcptrIndexStatus) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIndexStatus) SwigIsIndexStatus() {
}

func (p SwigcptrIndexStatus) DirectorInterface() interface{} {
	return nil
}

type IndriApiIndexStatusAction_code int
func _swig_getIndexStatus_FileOpen_IndexStatus() (_swig_ret IndriApiIndexStatusAction_code) {
	var swig_r IndriApiIndexStatusAction_code
	swig_r = (IndriApiIndexStatusAction_code)(C._wrap_FileOpen_IndexStatus_indri_go_8c4c74c3cec9541e())
	return swig_r
}

var IndexStatusFileOpen IndriApiIndexStatusAction_code = _swig_getIndexStatus_FileOpen_IndexStatus()
func _swig_getIndexStatus_FileSkip_IndexStatus() (_swig_ret IndriApiIndexStatusAction_code) {
	var swig_r IndriApiIndexStatusAction_code
	swig_r = (IndriApiIndexStatusAction_code)(C._wrap_FileSkip_IndexStatus_indri_go_8c4c74c3cec9541e())
	return swig_r
}

var IndexStatusFileSkip IndriApiIndexStatusAction_code = _swig_getIndexStatus_FileSkip_IndexStatus()
func _swig_getIndexStatus_FileError_IndexStatus() (_swig_ret IndriApiIndexStatusAction_code) {
	var swig_r IndriApiIndexStatusAction_code
	swig_r = (IndriApiIndexStatusAction_code)(C._wrap_FileError_IndexStatus_indri_go_8c4c74c3cec9541e())
	return swig_r
}

var IndexStatusFileError IndriApiIndexStatusAction_code = _swig_getIndexStatus_FileError_IndexStatus()
func _swig_getIndexStatus_FileClose_IndexStatus() (_swig_ret IndriApiIndexStatusAction_code) {
	var swig_r IndriApiIndexStatusAction_code
	swig_r = (IndriApiIndexStatusAction_code)(C._wrap_FileClose_IndexStatus_indri_go_8c4c74c3cec9541e())
	return swig_r
}

var IndexStatusFileClose IndriApiIndexStatusAction_code = _swig_getIndexStatus_FileClose_IndexStatus()
func _swig_getIndexStatus_DocumentCount_IndexStatus() (_swig_ret IndriApiIndexStatusAction_code) {
	var swig_r IndriApiIndexStatusAction_code
	swig_r = (IndriApiIndexStatusAction_code)(C._wrap_DocumentCount_IndexStatus_indri_go_8c4c74c3cec9541e())
	return swig_r
}

var IndexStatusDocumentCount IndriApiIndexStatusAction_code = _swig_getIndexStatus_DocumentCount_IndexStatus()
func DeleteIndexStatus(arg1 IndexStatus) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IndexStatus_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrIndexStatus) Status(arg2 int, arg3 string, arg4 string, arg5 int, arg6 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	C._wrap_IndexStatus_status_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_87)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_88)(unsafe.Pointer(&_swig_i_3)), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}

type IndexStatus interface {
	Swigcptr() uintptr
	SwigIsIndexStatus()
	DirectorInterface() interface{}
	Status(arg2 int, arg3 string, arg4 string, arg5 int, arg6 int)
}

type SwigcptrIndexEnvironment uintptr

func (p SwigcptrIndexEnvironment) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIndexEnvironment) SwigIsIndexEnvironment() {
}

func NewIndexEnvironment() (_swig_ret IndexEnvironment) {
	var swig_r IndexEnvironment
	swig_r = (IndexEnvironment)(SwigcptrIndexEnvironment(C._wrap_new_IndexEnvironment_indri_go_8c4c74c3cec9541e()))
	return swig_r
}

func DeleteIndexEnvironment(arg1 IndexEnvironment) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IndexEnvironment_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrIndexEnvironment) SetDocumentRoot(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_setDocumentRoot_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_89)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) SetAnchorTextPath(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_setAnchorTextPath_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_90)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) SetOffsetMetadataPath(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_setOffsetMetadataPath_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_91)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) SetOffsetAnnotationsPath(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_setOffsetAnnotationsPath_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_92)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) AddFileClass__SWIG_0(arg2 string, arg3 string, arg4 string, arg5 string, arg6 string, arg7 string, arg8 string, arg9 StringVector, arg10 StringVector, arg11 StringVector, arg12 StringVector, arg13 Std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9.Swigcptr()
	_swig_i_9 := arg10.Swigcptr()
	_swig_i_10 := arg11.Swigcptr()
	_swig_i_11 := arg12.Swigcptr()
	_swig_i_12 := arg13.Swigcptr()
	C._wrap_IndexEnvironment_addFileClass__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_93)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_94)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_95)(unsafe.Pointer(&_swig_i_3)), *(*C.swig_type_96)(unsafe.Pointer(&_swig_i_4)), *(*C.swig_type_97)(unsafe.Pointer(&_swig_i_5)), *(*C.swig_type_98)(unsafe.Pointer(&_swig_i_6)), *(*C.swig_type_99)(unsafe.Pointer(&_swig_i_7)), C.uintptr_t(_swig_i_8), C.uintptr_t(_swig_i_9), C.uintptr_t(_swig_i_10), C.uintptr_t(_swig_i_11), C.uintptr_t(_swig_i_12))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg5
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg6
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg7
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg8
	}
}

func (arg1 SwigcptrIndexEnvironment) GetFileClassSpec(arg2 string) (_swig_ret Indri_parse_FileClassEnvironmentFactory_Specification) {
	var swig_r Indri_parse_FileClassEnvironmentFactory_Specification
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Indri_parse_FileClassEnvironmentFactory_Specification)(SwigcptrIndri_parse_FileClassEnvironmentFactory_Specification(C._wrap_IndexEnvironment_getFileClassSpec_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_100)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrIndexEnvironment) AddFileClass__SWIG_1(arg2 Indri_parse_FileClassEnvironmentFactory_Specification) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IndexEnvironment_addFileClass__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (p SwigcptrIndexEnvironment) AddFileClass(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		p.AddFileClass__SWIG_1(a[0].(Indri_parse_FileClassEnvironmentFactory_Specification))
		return
	}
	if argc == 12 {
		p.AddFileClass__SWIG_0(a[0].(string), a[1].(string), a[2].(string), a[3].(string), a[4].(string), a[5].(string), a[6].(string), a[7].(StringVector), a[8].(StringVector), a[9].(StringVector), a[10].(StringVector), a[11].(Std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg_))
		return
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIndexEnvironment) DeleteDocument(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_deleteDocument_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrIndexEnvironment) SetIndexedFields(arg2 StringVector) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IndexEnvironment_setIndexedFields_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIndexEnvironment) SetNumericField__SWIG_0(arg2 string, arg3 bool, arg4 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_IndexEnvironment_setNumericField__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_101)(unsafe.Pointer(&_swig_i_1)), C._Bool(_swig_i_2), *(*C.swig_type_102)(unsafe.Pointer(&_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}

func (arg1 SwigcptrIndexEnvironment) SetNumericField__SWIG_1(arg2 string, arg3 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_IndexEnvironment_setNumericField__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_103)(unsafe.Pointer(&_swig_i_1)), C._Bool(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (p SwigcptrIndexEnvironment) SetNumericField(a ...interface{}) {
	argc := len(a)
	if argc == 2 {
		p.SetNumericField__SWIG_1(a[0].(string), a[1].(bool))
		return
	}
	if argc == 3 {
		p.SetNumericField__SWIG_0(a[0].(string), a[1].(bool), a[2].(string))
		return
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIndexEnvironment) SetOrdinalField(arg2 string, arg3 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_IndexEnvironment_setOrdinalField_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_104)(unsafe.Pointer(&_swig_i_1)), C._Bool(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) SetParentalField(arg2 string, arg3 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_IndexEnvironment_setParentalField_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_105)(unsafe.Pointer(&_swig_i_1)), C._Bool(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) SetMetadataIndexedFields(arg2 StringVector, arg3 StringVector) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IndexEnvironment_setMetadataIndexedFields_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIndexEnvironment) SetStopwords(arg2 StringVector) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IndexEnvironment_setStopwords_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIndexEnvironment) SetStemmer(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_setStemmer_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_106)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) SetMemory(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_setMemory_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.swig_type_107(_swig_i_1))
}

func (arg1 SwigcptrIndexEnvironment) SetNormalization(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_setNormalization_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrIndexEnvironment) SetStoreDocs(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_setStoreDocs_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrIndexEnvironment) Create__SWIG_0(arg2 string, arg3 IndexStatus) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IndexEnvironment_create__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_108)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) Create__SWIG_1(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_create__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_109)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (p SwigcptrIndexEnvironment) Create(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		p.Create__SWIG_1(a[0].(string))
		return
	}
	if argc == 2 {
		p.Create__SWIG_0(a[0].(string), a[1].(IndexStatus))
		return
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIndexEnvironment) Open__SWIG_0(arg2 string, arg3 IndexStatus) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IndexEnvironment_open__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_110)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) Open__SWIG_1(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_open__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_111)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (p SwigcptrIndexEnvironment) Open(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		p.Open__SWIG_1(a[0].(string))
		return
	}
	if argc == 2 {
		p.Open__SWIG_0(a[0].(string), a[1].(IndexStatus))
		return
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIndexEnvironment) Close() {
	_swig_i_0 := arg1
	C._wrap_IndexEnvironment_close_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrIndexEnvironment) AddFile__SWIG_0(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IndexEnvironment_addFile__SWIG_0_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_112)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrIndexEnvironment) AddFile__SWIG_1(arg2 string, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_IndexEnvironment_addFile__SWIG_1_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_113)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_114)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func (p SwigcptrIndexEnvironment) AddFile(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		p.AddFile__SWIG_0(a[0].(string))
		return
	}
	if argc == 2 {
		p.AddFile__SWIG_1(a[0].(string), a[1].(string))
		return
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIndexEnvironment) AddString(arg2 string, arg3 string, arg4 Std_vector_Sl_indri_parse_MetadataPair_Sg_) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (int)(C._wrap_IndexEnvironment_addString_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), *(*C.swig_type_115)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_116)(unsafe.Pointer(&_swig_i_2)), C.uintptr_t(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrIndexEnvironment) AddParsedDocument(arg2 ParsedDocument) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_IndexEnvironment_addParsedDocument_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrIndexEnvironment) DocumentsIndexed() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_IndexEnvironment_documentsIndexed_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIndexEnvironment) DocumentsSeen() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_IndexEnvironment_documentsSeen_indri_go_8c4c74c3cec9541e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type IndexEnvironment interface {
	Swigcptr() uintptr
	SwigIsIndexEnvironment()
	SetDocumentRoot(arg2 string)
	SetAnchorTextPath(arg2 string)
	SetOffsetMetadataPath(arg2 string)
	SetOffsetAnnotationsPath(arg2 string)
	GetFileClassSpec(arg2 string) (_swig_ret Indri_parse_FileClassEnvironmentFactory_Specification)
	AddFileClass(a ...interface{})
	DeleteDocument(arg2 int)
	SetIndexedFields(arg2 StringVector)
	SetNumericField(a ...interface{})
	SetOrdinalField(arg2 string, arg3 bool)
	SetParentalField(arg2 string, arg3 bool)
	SetMetadataIndexedFields(arg2 StringVector, arg3 StringVector)
	SetStopwords(arg2 StringVector)
	SetStemmer(arg2 string)
	SetMemory(arg2 int64)
	SetNormalization(arg2 bool)
	SetStoreDocs(arg2 bool)
	Create(a ...interface{})
	Open(a ...interface{})
	Close()
	AddFile(a ...interface{})
	AddString(arg2 string, arg3 string, arg4 Std_vector_Sl_indri_parse_MetadataPair_Sg_) (_swig_ret int)
	AddParsedDocument(arg2 ParsedDocument) (_swig_ret int)
	DocumentsIndexed() (_swig_ret int)
	DocumentsSeen() (_swig_ret int)
}


type SwigcptrIndri_infnet_EvaluatorNode_MResults uintptr
type Indri_infnet_EvaluatorNode_MResults interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIndri_infnet_EvaluatorNode_MResults) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_indri_parse_MetadataPair_Sg_ uintptr
type Std_vector_Sl_indri_parse_MetadataPair_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_indri_parse_MetadataPair_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIndri_parse_FileClassEnvironmentFactory_Specification uintptr
type Indri_parse_FileClassEnvironmentFactory_Specification interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIndri_parse_FileClassEnvironmentFactory_Specification) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_ uintptr
type Std_vector_Sl_indri_api_ScoredExtentResult_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_indri_api_ScoredExtentResult_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg_ uintptr
type Std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_indri_api_DocumentVector_Sm__Sg_ uintptr
type Std_vector_Sl_indri_api_DocumentVector_Sm__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_indri_api_DocumentVector_Sm__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_indri_api_ParsedDocument_Sm__Sg_ uintptr
type Std_vector_Sl_indri_api_ParsedDocument_Sm__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_indri_api_ParsedDocument_Sm__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

